sudo apt-get update && sudo apt-get upgrade -y || exit 1 || echo 'Error to update and upgrade, please check your internet connection'
sudo tar -xvf *.tar || exit 1 || echo 'Error to unpack code.tar file, please check if the file exist or if it is corrupted'
cat requeriments_linux.list | xargs sudo apt-get install -y || exit 1 || echo 'Error to install packages, please check your internet connection'
yes | sudo pip3 install -r requeriments_python.txt || exit 1 || echo 'Error to install packages, please check your internet connection'
sudo mkdir /home/pi/code/measure /home/pi/code/sort /home/pi/code/log /home/pi/code/send /home/pi/code/dbc /home/pi/code/restore /media/my_usb/ || echo 'Error to create folders, please check'
sudo mv -v /home/pi/code/*.service /etc/systemd/system/ || echo 'Error to move services, please check'
sudo mv /home/pi/code/*.dbc /home/pi/code/dbc || echo 'Error to move dbc files, please check'
sudo chmod u+x /home/pi/code/*.sh || echo 'Error to check permission'
sudo systemctl start dbc_decoder.service measure.service starter_mf4.service zip_sd.service cloud.service || echo 'Error to start services, please check'
sudo systemctl enable dbc_decoder.service measure.service starter_mf4.service zip_sd.service cloud.service || echo 'Error to enable services, please check'
printf "\ndtparam=spi=on\ndtoverlay=mcp2515-can0,oscillator=8000000,interrupt=25\ndtoverlay=spi1-1cs" | sudo tee -a /boot/config.txt || echo 'Error to configure CAN, please check'
printf "\nauto can0\niface can0 can static\n    bitrate 250000" | sudo tee -a /etc/network/interfaces || echo 'Error to configure CAN, please check'
